#!/bin/bash

REQUEST=$1
PARAMETER=$2
if [[ "$REQUEST" = "core:update" ]]
then
  git pull origin main
  composer update

elif [[ "$REQUEST" = "cc" ]]
then
  ./bin/console cache:clear
  ./bin/console si:se caching $PARAMETER

elif [[ "$REQUEST" = "services" ]]
then
  ./bin/console si:se

elif [[ "$REQUEST" = "dr" ]]
then
  ./bin/console debug:router

elif [[ "$REQUEST" = "install" ]]
then

  if [ ! -f ".env.local" ]
  then
echo 'APP_ENV=prod
APP_SITE=example_com
APP_LAYOUT=example_com
APP_STYLE_GUIDE=true
APP_SECRET="Add 32 characters without spaces"

APP_REST_API="Rest URL without HTTP"
APP_REST_CLIENT_DOMAIN="Username"
APP_REST_CLIENT_KEY="Rest API"' > .env.local
  fi

  composer update;
  ./bin/console si:se install
  ./bin/console si:se update test
  ./bin/console cache:clear

elif [[ "$REQUEST" = "update" ]]
then
  ./bin/console si:se update $PARAMETER
  ./bin/console cache:clear

elif [[ "$REQUEST" = "start" ]]
then
  cd ./public
  php -S localhost:8000 index.php

elif [[ "$REQUEST" = "stop" ]]
then
  kill $(ps aux | grep 'php -S localhost:8000 index.php' | awk '{print $2}') 

elif [[ "$REQUEST" = "help" ]]
then
   ./bin/console si:se

else
  echo ""
  echo " =============================================================="
  echo " General Information."
  echo " =============================================================="
  echo " Version                                                  alpha"
  echo " Dependencies                     PHP 8.1 and up, composer, git"
  echo " =============================================================="
  echo ""
  echo ""
  echo " =============================================================="
  echo " Site Commands."
  echo " =============================================================="
  echo " Services offered by system                     'site services'"
  echo " Clear caches alias                                   'site cc'"
  echo " Debug route alias                                    'site dr'"
  echo " Install latest core release                 'site core:update'"
  echo " Site installation                               'site install'"
  echo " Start testing web server                          'site start'"
  echo " Stop testing web server                  Ctrl C or 'site stop'"
  echo " Update custom site configuration                 'site update'"
  echo " =============================================================="
  echo ""
fi
