#!/bin/bash

REQUEST=$1
if [[ "$REQUEST" = "core:update" ]]
then
  echo "Update core";
  git pull origin main
  composer update

elif [[ "$REQUEST" = "c:c" ]]
then
  ./bin/console cache:clear

elif [[ "$REQUEST" = "d:r" ]]
then
  ./bin/console debug:router

elif [[ "$REQUEST" = "install" ]]
then
  echo "Site installation";
  composer update;
  ./bin/console si:se install
  ./bin/console si:se update

  if [ ! -f ".env.local" ]
  then
echo 'APP_ENV=prod
APP_ENABLED_SITE=example_com
APP_STYLE_GUIDE=true
APP_SECRET="Add 32 characters without spaces"

APP_REST_API="Rest URL without HTTP"
APP_REST_CLIENT_DOMAIN="Username"
APP_REST_CLIENT_KEY="Rest API"' > .env.local
  fi

elif [[ "$REQUEST" = "update" ]]
then
  ./bin/console si:se update

elif [[ "$REQUEST" = "start" ]]
then
  cd ./public
  php -S localhost:8000 index.php

elif [[ "$REQUEST" = "stop" ]]
then
  kill $(ps aux | grep 'php -S localhost:8000 index.php' | awk '{print $2}') 

else
  echo ""
  echo " =============================================================="
  echo " Commands"
  echo " =============================================================="
  echo " Clear caches alias                                  'site c:c'"
  echo " Debug route alias                                   'site d:r'"
  echo " Install latest core release                 'site core:update'"
  echo " Site installation                               'site install'"
  echo " Start testing web server                          'site start'"
  echo " Stop testing web server                  Ctrl C or 'site stop'"
  echo " Update custom site configuration                 'site update'"
  echo " =============================================================="
  echo ""
fi
